### ISSUE TITLE
Allow processing steps to be ordered in metadata

### ISSUE THREAD

**Issue by jpgill86** [jpgill86/neurotic#146]
A revised metadata format like this could allow the order of operations to be controlled by the user, and even for processing stages to be repeated:

```yaml
my dataset:
    # file details

    processing:  # lazy=False only
        - filter:
            # filter parameters
        - amplitude_discriminators:
            # spike detection parameters
        - filter:
            # second set of filter parameters
```
