### ISSUE TITLE
Allow events and epochs to be defined directly in the metadata

### ISSUE THREAD

**Issue by jpgill86** [jpgill86/neurotic#158]
For example,

```yaml
my dataset:
    # ...
    events:
        - name: My event list
          label: Here something happened
          time: 10 # sec
        - name: My event list
          label: Here something different happened
          time: 20 # sec
    epochs:
        # etc
```
